// NAF code → sector label (matched on the 2-digit division prefix).

const NAF_SECTORS = {
  '01': 'Agriculture',
  '02': 'Sylviculture',
  '03': 'Pêche & aquaculture',
  '05': 'Extraction de charbon',
  '06': 'Extraction d\'hydrocarbures',
  '07': 'Extraction de minerais',
  '08': 'Autres industries extractives',
  '09': 'Services extraction',
  '10': 'Industrie alimentaire',
  '11': 'Boissons',
  '12': 'Tabac',
  '13': 'Textile',
  '14': 'Habillement',
  '15': 'Cuir & chaussure',
  '16': 'Bois & papier',
  '17': 'Papier & carton',
  '18': 'Imprimerie',
  '19': 'Raffinage de pétrole',
  '20': 'Chimie',
  '21': 'Pharmacie',
  '22': 'Caoutchouc & plastique',
  '23': 'Minéraux non métalliques',
  '24': 'Métallurgie',
  '25': 'Fabrication métallique',
  '26': 'Électronique & informatique',
  '27': 'Équipements électriques',
  '28': 'Machines & équipements',
  '29': 'Automobile',
  '30': 'Autres matériels de transport',
  '31': 'Meubles',
  '32': 'Autres industries',
  '33': 'Réparation industrielle',
  '35': 'Énergie',
  '36': 'Eau',
  '37': 'Assainissement',
  '38': 'Collecte & traitement des déchets',
  '39': 'Dépollution',
  '41': 'Promotion immobilière',
  '42': 'Génie civil',
  '43': 'Travaux spécialisés',
  '45': 'Commerce automobile',
  '46': 'Commerce de gros',
  '47': 'Commerce de détail',
  '49': 'Transport terrestre',
  '50': 'Transport maritime',
  '51': 'Transport aérien',
  '52': 'Logistique & entreposage',
  '53': 'Courrier & livraison',
  '55': 'Hébergement',
  '56': 'Restauration',
  '58': 'Édition',
  '59': 'Production audiovisuelle',
  '60': 'Audiovisuel',
  '61': 'Télécommunications',
  '62': 'Informatique & logiciels',
  '63': 'Services d\'information',
  '64': 'Finance & banque',
  '65': 'Assurance',
  '66': 'Auxiliaires financiers',
  '68': 'Immobilier',
  '69': 'Juridique & comptabilité',
  '70': 'Direction d\'entreprises',
  '71': 'Architecture & ingénierie',
  '72': 'Recherche & développement',
  '73': 'Publicité & marketing',
  '74': 'Activités spécialisées',
  '75': 'Vétérinaires',
  '77': 'Location & crédit-bail',
  '78': 'Emploi & RH',
  '79': 'Tourisme & voyages',
  '80': 'Sécurité & surveillance',
  '81': 'Services aux bâtiments',
  '82': 'Services administratifs',
  '84': 'Administration publique',
  '85': 'Enseignement',
  '86': 'Santé humaine',
  '87': 'Hébergement médico-social',
  '88': 'Action sociale',
  '90': 'Arts & spectacles',
  '91': 'Bibliothèques & musées',
  '92': 'Jeux & paris',
  '93': 'Sports & loisirs',
  '94': 'Organisations associatives',
  '95': 'Réparation informatique',
  '96': 'Services personnels',
};

/** Returns a human-readable sector label for a NAF code, or null if not found. */
function nafToSector(nafCode) {
  if (!nafCode) return null;
  const prefix = nafCode.replace('.', '').substring(0, 2);
  return NAF_SECTORS[prefix] || null;
}
